import type { Metadata } from 'next'
import { ReduxProvider } from "@/store/provide";
import { Inter } from 'next/font/google'
import './globals.css'
import '../styles/Landing.css'
import '../styles/SideBar.css'
import '../styles/Add.css'
import '../styles/addFlights.css'
import '../styles/Airlines.css'
import '../styles/Chat.css'
import 'react-toastify/dist/ReactToastify.css';

import 'mdb-react-ui-kit/dist/css/mdb.min.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Admin App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={inter.className}><ReduxProvider>{children}</ReduxProvider></body>
    </html>
  )
}
