
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../styles/landing.css";
import "../styles/Navbar.css";
import "../styles/SignUp.css";
import "../styles/header.css";
import "../styles/PassengerInfo.css";
import { Provider } from "react-redux";
import { ReduxProvider } from "@/store/provide";
import { ToastContainer } from "react-toastify";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
